redhat-developer/app-services-guides

rhoas-cli/README.adoc
Added link text for a couple links to improve accessibility.
=> Update rhoas cli getting started guide for accessibility

.build/package-lock.json, .build/package.json, .build/src/app/QuickStartDrawerFederated.tsx
Which lets us control where to insert the drawer from application-services-ui
Relevant PRs:
https://gitlab.cee.redhat.com/mk-ci-cd/application-services-ui/-/merge_requests/57
https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/422
https://github.com/redhat-developer/app-services-guides/pull/91
=> forward new appendTo prop to quickstart

kafka-quarkus-dev/README.adoc
* fix the clone cmd
* fix the path to the sample app
=> Fix Kafka Quarkus Dev QuickStart

getting-started/README.adoc
@bhardesty Would you mind? New UI changes I found during today's testing hosted by Jen G.
=> Update getting started per latest UI in testing

.github/workflows/code-examples-kafka-quickstart.yml, code-examples/quarkus-kafka-quickstart/README.md
original config did not work. Realized that after merge.
Need another merge to check
=> fix: Update build trigger of kafka source code to wildcard

code-examples/quarkus-kafka-quickstart/.kubernetes/kubernetes.yml
Added route to template.
CC @b1zzu
=> fix: add route to kuberentes template

code-examples/quarkus-kafka-quickstart/pom.xml, code-examples/quarkus-kafka-quickstart/src/main/resources/application.properties
Fixing bug that did build image for local development. I have disabled properties (keeping them there for users to change if needed)
=> Container improvements

kafka-bin-scripts/README.adoc, kafka-quarkus-dev/README.adoc
Addresses #113 reported by @b1zzu and @wtrocki . So @wtrocki @b1zzu @pmuir @bhardesty Can you please review and verify?
=> Add Windows note to quarkus and bin scripts qs

devsandbox-quickstarts/rhosak-devsandbox-getting-started-quickstart.yaml, getting-started/README.adoc, kafka-bin-scripts/README.adoc, kafkacat/README.adoc, quarkus/README.adoc
@bhardesty If you're up for another? Wanted to put this in front of you in case of any impact on other docs besides these few quick starts. Also note the slight change in the Welcome intro text per the hackathon feedback. I agree there too, so made that change in all 4 quick starts. Let me know what you think.
=> Fixes and improvements from Quarkus qs hackathon.

kafka-bin-scripts/README.adoc, kafka-bin-scripts/quickstart.yml, kafkacat/README.adoc, quarkus/README.adoc, quarkus/quickstart.yml
@bhardesty The prereq fixes per our conversation. Would you mind reviewing and approving if good? Thanks.
=> Fix prereq issues for Summit

kafka-bin-scripts/README.adoc
Added "qs" condition to the verification for the first procedure so that it doesn't show up when rendered outside of the UI.
=> Fix conditionalization in verification step

CONTRIBUTING.adoc, service-discovery/README.adoc, service-discovery/quickstart.yml
This is what caused the build to fail
=> fix: don’t use conflicting section ids

rhoas-cli/README.adoc
This needs to be merged once new CLI release will be done
=> BREAKING: CLI commands to hyphenated form

consumer-configuration/README.adoc
Renaming the consumer group commands
=> [DOC] CLI: consumer group command name update

.build/src/app/QuickStartDrawerFederated.tsx
=> add additional check for root

.build/package-lock.json, .build/package.json, .build/src/app/Catalog.css, .build/src/app/QuickStartCatalogFederated.tsx, .build/src/app/QuickStartDrawerFederated.tsx, .build/src/app/procedure-parser.ts, .build/src/app/quickstartLoader.tsx
=> Qs upgrade followup

getting-started/README.adoc
Updating **Instance name** to **Name** as per the Jira issue https://issues.redhat.com/browse/MGDSTRM-4897 and doc https://docs.google.com/document/d/1gVd_dQrap0T78Tk-kZs2cJqL0zGAedpaME9CSTmI8zs/edit#
=> Updating Instance name to Name

rhoas-cli/README.adoc
=> Update commands for managing kafka in cli getting started

consumer-configuration/README.adoc
Updates the _Configuring consumer groups_ content to include reset and delete operations from CLI and UI.
=> docs: delete and reset updates for consumer groups

getting-started-service-registry/README.adoc
Raised by @jciroli-rh during sanity check, fixing urgently per request. Leaving for decision whether to merge now or wait till after the block.
=> Fix broken SR link to portal.

README.adoc
Adds links to the new CLI guides
=> docs: updated readme with new CLI doc

rhoas-cli-kafka/README.adoc, rhoas-cli-service-registry/README.adoc
Adds an ID to the prereqs sections of the CLI getting started guides
=> docs: cli guide mod doc fix

.build/src/app/procedure-parser.ts, .build/src/app/quickstartLoader.tsx
* don’t load images that we don’t need
* fix the path for images we do need
=> fix: improve the image handling

rhoas-cli-kafka/README.adoc
Update to ACL table format to coincide with https://github.com/redhat-developer/app-services-cli/pull/1292
=> use update ACL table format

getting-started/README.adoc
Fixes bug reported in [MGDSTRM-6388](https://issues.redhat.com/browse/MGDSTRM-6388).
=> Fix metrics content for now.

.build/package-lock.json, .build/package.json
This dependency was missing so I could not run the guides locally:
```shell
$ webpack serve --hot --color --progress --config webpack.dev.js
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
```
=> Add missing dependency

topic-configuration/README.adoc
Changed two sect IDs but missed updating two existing cross-references.
Fixed these and tested the updated links on my fork.
=> Fix two links

consumer-configuration/README.adoc, getting-started-service-registry/README.adoc, getting-started/README.adoc, kafka-bin-scripts/README.adoc, kafkacat/README.adoc, metrics-monitoring/README.adoc, nodejs/README.adoc, quarkus/README.adoc, service-discovery/README.adoc
Jira: https://issues.redhat.com/browse/MGDSTRM-6928
=> Add missing metadata

docs/kafka/access-mgmt-kafka/README.adoc, docs/kafka/getting-started-kafka/README.adoc
Updated access management content per latest changes in UI with predefined permission options.
Doc previews:
* [Managing access](http://file.rdu.redhat.com/~sterobin/MGDSTRM-access-mgmt/README.html)
* [Getting started > Setting permissions](http://file.rdu.redhat.com/~sterobin/MGDSTRM-getting-started/README.html#proc-setting-service-account-permissions_getting-started)
Jira: https://issues.redhat.com/browse/MGDSTRM-5849
=> Access mgmt updates february

docs/kafka/metrics-monitoring-kafka/README.adoc
Expanded metrics descriptions per feedback from Mickael Maison in [google doc](https://docs.google.com/document/d/1V_E9G-SULu_zZCNlQ2FF-3TgunOZLatLNMiKsnnAIwA/edit).
[Doc preview](http://file.rdu.redhat.com/~sterobin/MGDSTRM-metrics-monitoring/README.html#ref-supported-metrics_monitoring-metrics)
[Jira](https://issues.redhat.com/browse/MGDSTRM-7243)
=> Update metrics descriptions

docs/kafka/kafka-bin-scripts-kafka/README.adoc
Made minor changes using simpler and less formal language. Also moved sentences so they showed after code snippets instead of before them.
=> Updated some text in README.adoc to improve clarity and consistency.

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc, docs/registry/rhoas-cli-getting-started-registry/README.adoc, docs/rhoas/rhoas-cli-installation/README.adoc
@jbyrne-redhat @bredamc @wtrocki This is the former PR 399, with all of your review comments incorporated.
=> Rework command output in CLI guides

docs/kafka/access-mgmt-kafka/README.adoc, docs/kafka/getting-started-kafka/README.adoc
Fixes a bug I introduced from a misunderstanding of functionality.
=> Fix access instruction

docs/kafka/metrics-monitoring-kafka/README.adoc
feat: replaced no longer exposed messages and bytes metrics by newly added replacement metrics
=> feat: replaced no longer exposed messages and bytes metrics by newly added replacement metrics

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc
Amended admonition block in Creating a Kafka topic step, removed 4 spaces from json code snippet, and clarified service-account and clientID correlation in Creating a service account step.
=> Implemented QE Review feedback for Getting started with the rhoas CLI for Red Hat OpenShift Streams for Apache Kafka

docs/kafka/getting-started-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc
new note added after creating a topic to alert users if the broker is down
=> new note added after creating a topic to alert users if the broker is down

code-examples/quarkus-kafka-quickstart/src/main/resources/application.properties, code-examples/quarkus-service-registry-quickstart/consumer/src/main/resources/application.properties, code-examples/quarkus-service-registry-quickstart/producer/src/main/resources/application.properties, docs/kafka/kcat-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc, docs/kafka/quarkus-kafka/README.adoc, docs/registry/quarkus-registry/README.adoc
To be merged after `rhoas context` commands are released.
=> docs: update env vars acording to CLI output

docs/kafka/consumer-configuration-kafka/README.adoc
resetting consumer group offset has been updated to appear as it does in the UI and replaced custom offset with absolute
=> resetting consumer group offset has been updated 

code-examples/quarkus-kafka-quickstart/src/main/resources/application.properties, code-examples/quarkus-service-registry-quickstart/consumer/src/main/resources/application.properties, code-examples/quarkus-service-registry-quickstart/producer/src/main/resources/application.properties, docs/kafka/kcat-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc, docs/kafka/quarkus-kafka/README.adoc, docs/registry/quarkus-registry/README.adoc
Reverts redhat-developer/app-services-guides#448
We need to revert changes as service registry and kafka using different oauth url
=> Revert "docs: update env vars acording to CLI output"

docs/kafka/consumer-configuration-kafka/README.adoc
Moved existing note to the beginning and added new content for Listing consumer groups
@mmurphy@redhat.com, please review
=> Listing consumer groups

CONTRIBUTING.adoc
Text amended to reflect correct name of button.
=> Amended text of step 5 in Releases section of Contributing doc

code-examples/quarkus-service-registry-quickstart/producer/src/main/resources/application.properties, docs/registry/quarkus-registry/README.adoc
Follow up to #469
Updates examples and docs to use Core Registry API endpoint.
=> docs: update registry guides accoring to CLI outputs

docs/kafka/metrics-monitoring-kafka/README.adoc
New trial and production instance limit values added.
=> Added information about trial and production instance limits

docs/kafka/service-binding-kafka/README.adoc
- This PR was something of a proof-of-concept to measure the effort involved in reviewing a large guide against our [style guidelines](https://docs.google.com/document/d/1TERH4XRH6La44hUQH88LUaax-35JH3dLXmceGJoLv7I/edit#) and make any required updates.
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-8825/README.html).
- The JIRA is [here](https://issues.redhat.com/browse/MGDSTRM-8825).
=> docs: Apply MAS doc style updates to RHOSAK service binding guide

docs/kafka/nodejs-kafka/README.adoc
Update environment variables and filename according to output generated by the `rhoas generate-config` command.
The examples have been updated.
=> docs(nodejs-kafka): update env variables according to CLI output

docs/kafka/topic-configuration-kafka/README.adoc
Luke Chen, ready for your SME review. I've applied the policy updates from [MGDSTRM-7712](https://issues.redhat.com/browse/MGDSTRM-7712) to the topic configs doc. I've also pinged you with a few specific questions. Can you have a look through to verify this PR? Thanks.
Links:
- [Jira](https://issues.redhat.com/browse/MGDSTRM-8526)
- [Doc preview](http://file.rdu.redhat.com/~sterobin/JK-8526/README.html#ref-supported-topic-properties_configuring-topics)
=> Update topic properties

docs/kafka/topic-configuration-kafka/README.adoc
@jbyrne-redhat Ready for your review. Here's the [doc preview](http://file.rdu.redhat.com/~sterobin/JK-8526/README.html). I've left a few specific comments just FYI. Thanks.
=> Update style issues in topic config doc

README.adoc, docs/kafka/getting-started-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc, docs/kafka/quarkus-kafka/README.adoc, docs/registry/quarkus-registry/README.adoc
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JR-400/README.html)
=> docs: Updates to Quarkus quick start for Service Registry to describe manual connection use case

docs/kafka/service-binding-kafka/README.adoc, docs/registry/service-binding-registry/README.adoc
Verified output with Asciidoctor. See [here](http://file.emea.redhat.com/~jbyrne/remove-cred-info/service-binding-kafka.html) and [here](http://file.emea.redhat.com/~jbyrne/remove-cred-info/service-binding-registry.html).
=> docs: Update credential info in service binding guides

README.adoc, docs/registry/access-mgmt-registry/README.adoc
- Add admin task for registry instance settings to access guide 
- Fix broken link to registry CLI guide in top-level readme
- Add peer review feedback on entire SR access guide for consistency
=> Add registry settings admin task to access guide

docs/api-designer/getting-started-api-designer/README.adoc
Reverts redhat-developer/app-services-guides#556
=> Revert "MGDSR-416: Testing RHOAD QS"

docs/kafka/getting-started-kafka/README.adoc, docs/kafka/kafka-bin-scripts-kafka/README.adoc, docs/kafka/kcat-kafka/README.adoc, docs/kafka/metrics-monitoring-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc, docs/kafka/quarkus-kafka/README.adoc
Also includes some other minor style updates.
=> Docs: Update faulty references to location of Service Accounts page

docs/kafka/getting-started-kafka/README.adoc
From conversation with @riccardo-forina, I need to merge something upstream to trigger a rebuild of the stage UI. Applying these minor style changes for that purpose.
=> Docs: Minor style updates

docs/kafka/quarkus-kafka/README.adoc
Amended section is the **Configuring** the Quarkus example application to connect to a Kafka **instance** section.
=> Removed conditional statement so prerequisites appear in quickstart

code-examples/helm-kafka-example/.helmignore, code-examples/helm-kafka-example/Chart.yaml, code-examples/helm-kafka-example/README.md, code-examples/helm-kafka-example/templates/deployment.yaml, code-examples/helm-kafka-example/templates/service.yaml, code-examples/helm-kafka-example/values.yaml, docs/rhoas/rhoas-helm-guide/README.adoc
Contents of the external repo has been moved to `code-examples`.
=> feat: add example helm chart

docs/kafka/kafka-bin-scripts-kafka/README.adoc
- Applies [MAS style guidelines](https://docs.google.com/document/d/1TERH4XRH6La44hUQH88LUaax-35JH3dLXmceGJoLv7I/edit?pli=1#heading=h.v8qjgp8tzewa) to the Kafka scripts quick start
- Streamlines the text of the quick start where possible
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-9706/README.html)
=> docs: JK-9706: apply style updates to Kafka scripts quick start

docs/kafka/kafka-bin-scripts-kafka/README.adoc
Preview available [here](http://file.ams.redhat.com/aecollin/JK-9922/README.html).
=> Replaced SASL/PLAIN with OAUTH as recommended authentication mechanism.

docs/kafka/getting-started-kafka/README.adoc
Preview available [here](http://file.ams.redhat.com/aecollin/JK-9956/README.html).
=> Amended Tech Preview text in line with CCS guidelines.

docs/kafka/getting-started-kafka/README.adoc, docs/kafka/nodejs-kafka/README.adoc, docs/kafka/quarkus-kafka/README.adoc
- Applies [MAS style guidelines](https://docs.google.com/document/d/1TERH4XRH6La44hUQH88LUaax-35JH3dLXmceGJoLv7I/edit#) to the Kafka _Getting Started_ quick start
- Reflects some of the style updates to the Kafka _Quarkus_ and _Node.js_ quick starts
- An HTML preview build of the Getting Started quick start is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-9560/README.html)
=> docs: apply style updates to Kafka Getting Started quick start

docs/kafka/access-mgmt-kafka/README.adoc
Updated intro to guide as per recommendations from [MGDSTRM-9861](https://issues.redhat.com/browse/MGDSTRM-9861).
Note to reviewers: preview available [here](http://file.ams.redhat.com/aecollin/JK-9861/README.html).
=> Updated access permissions intro in Managing Access guide.

docs/registry/quarkus-registry/README.adoc
- PR makes style updates to mirror those made to the Quarkus quick start for RHOSAK
- Some other, minor suggested wording updates
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JR-547/Using%20Quarkus%20applications%20with%20Kafka%20instances%20and%20OpenShift%20Service%20Registry.html)
=> docs: make style updates for rhosr quarkus quick start

docs/kafka/metrics-monitoring-kafka/README.adoc
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-10491/Monitoring%20metrics%20in%20OpenShift%20Streams%20for%20Apache%20Kafka.html)
=> docs: JK-10491: improve appearance of supported metrics reference section

docs/kafka/metrics-monitoring-kafka/README.adoc
- SME review already completed offline. See this [Google doc](https://docs.google.com/document/d/1ebxyWxPQaVRNKH9BnZHEe5FKe7JloVNr0kd7rN72DJc/edit?usp=sharing).
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-10248/Monitoring%20metrics%20in%20OpenShift%20Streams%20for%20Apache%20Kafka.html).
=> docs: JK-10248: add two new partition size metrics

docs/registry/getting-started-registry/README.adoc
Note to reviewers: HTML preview [here](http://file.ams.redhat.com/aecollin/JR-634/README.html).
=> docs: JR-634: Added note about access permissions to step 1 of GS guide
