redhat-developer/app-services-guides

README.adoc

Note that the service-binding guide doesn't appear to exist anymore. I didn't remove it from the README because I'm not sure if it will be coming back.

Fix quarkus guide link in README

---

rhoas-cli/README.adoc

When split by asciidoc-splitter, a line break is removed between the intro and the first include. Asciidoctor can't process this correctly, because it's ambiguous whether the first include is part of the bulleted list or not. To fix the issue, I've enclosed the bulleted list in an open block to explicitly set it off from the subsequent include.

Fix line break in rhoas-cli guide

---

rhoas-cli/README.adoc

Some of the links in the rhoas CLI guide still point to the bf3 repo. I changed them to point to the app-services-cli repo.

Update links in rhoas cli guide

---

kafka-bin-scripts/README.adoc

Fixes a typo in the anchor ID of the final section.

Fix typo in bin scripts quick start

---

kafka-bin-scripts/README.adoc

Previously, the Kafka bin scripts quick start stated that when running kafka-console-producer.sh, the topic would be created automatically. However, this is no longer true as the Kafka instances do not support topic auto-creation. I added a step to create the topic manually using kafka-topics.sh so that messages can be produced and consumed on it.

Fix topic creation in Kafka bin scripts quick start

---

devsandbox-quickstarts/rhosak-devsandbox-connect-cli-toolscontainer-quickstart.yaml
devsandbox-quickstarts/rhosak-devsandbox-getting-started-quickstart.yaml
devsandbox-quickstarts/rhosak-devsandbox-kafkacat-toolscontainer.yaml

Two more quickstarts to be deployed on DevSandbox and to be used for the Summit RHOSAK workshop.
The contents is very similar to the existing `Getting started` and `kafkacat` quickstarts, but adaptd to the workshop (kafka cluster already provisioned, kafkacat on installed a tools image).

Quickstarts for DevSandbox

---

kafka-bin-scripts/README.adoc

The Kafka distribution includes Windows-versions of the bin scripts. I added a note about this so that any potential Windows users are aware.

Add note about using the bin scripts on Windows

---

.build/package-lock.json

I ran an `npm audit fix` which will hopefully (🤞🏻) remove the ugly warning banner on the repo homepage. If not we can probably dismiss the warnings through the GitHub UI.

chore: fix npm security warnings

---

rhoas-cli/README.adoc

Update the version number to 0.24.1 (the current version).
There are a couple examples that show how to install an older version of the CLI. I changed those version numbers to 0.23.1 (the first "production" version).

Update rhoas version number in CLI getting started guide

---

devsandbox-quickstarts/rhosak-devsandbox-getting-started-quickstart.yaml
getting-started/README.adoc
quarkus/README.adoc

Addresses the following Jiras:
* https://issues.redhat.com/browse/MGDSTRM-3039 - Remove note about number of partitions
* https://issues.redhat.com/browse/MGDSTRM-3022 - Clarify Kafkacat with stdin
@b1zzu Can you please review and verify? Fixes your reported bugs.
@b1zzu However, can you please clarify what changes you're suggesting for the `stdin` bit, something about using a `|` instead? I don't follow. Here's how it currently reads:
```
. On the command line, enter the following commands to start Kafkacat in _producer_ mode. This mode enables you to produce messages to your Kafka topic.
+
--
This example uses the SASL/PLAIN authentication mechanism with the server and credential environment variables that you set previously. This example produces messages to a topic in {product} named …
```

Remove note about partitions

---

rhoas-cli/README.adoc

The rhoas CLI install guide was using a mix of three different versions. This PR changed them all to use the current latest version.

use consistent rhoas CLI version

---

getting-started/README.adoc
getting-started/quickstart.yml
kafka-bin-scripts/README.adoc
kafka-bin-scripts/quickstart.yml
kafkacat/README.adoc
kafkacat/quickstart.yml

@pmuir @bhardesty, I got a ping from @jgiardino about the following user feedback for the bin scripts quick start:
>The prerequisites mention only latest JDK for Windows, but I'm on macOS. I'd say we need to add the requirement for the latest JDK regardless of the OS.
He's referring to the Oracle JDK prereq which is mentioned "For Windows". In the Quarkus quick start, we mention both JDK 11+ and Oracle JDK for Windows but in the bin scripts we mention only the Oracle JDK for Windows, nothing about JDK 11+. So I _think_ the user is confused because he's misreading that to mean the JDK 11? Or does the Oracle JDK apply to MacOS too? I've pushed this PR to add the JDK 11 prereq to the bin scripts quick start. Is this the right way to clarify so that it's clear what applies to Windows only, or …

Add JDK prereq to bin scripts.

---

rhoas-cli/README.adoc

Updates the CLI version references from `0.24.3` to `0.25.0` in the _Getting started with the rhoas CLI_ guide.

[DOC] update the CLI version references

---

rhoas-cli/README.adoc

This eliminates the use of xrefs, and instead uses the same linking mechanism as the quick starts.

Change "xref" to "link" in CLI getting started guide

---

kafka-bin-scripts/README.adoc
kafkacat/README.adoc
quarkus/README.adoc

Updates the quickstarts to include _group ID_ configuration for consumer groups.

[DOC] add group ID config to quickstarts

---

.github/workflows/node.js.yml
CONTRIBUTING.adoc
README.adoc
code-examples/quarkus-kafka-quickstart/README.md
getting-started/README.adoc
quickstart.schema.json

Details in [Jira](https://issues.redhat.com/browse/MAKDOC-277). I ensured that globally we are saying "quick start" two words, lowercase, except in headings ("Quick start"), and except in certain code that specifically uses one word as part of the build requirements and resource names, such as `QuickStart`, etc.

Update "quick start" capitalization and spacing for consistency, and some broken community links

---

quarkus/README.adoc

fixes #291 
GROUP_ID env variable is not used in quarkus. It is also not documented causing some issues with completing guide.

chore: remove invalid env variable

---

getting-started/README.adoc
kafka-bin-scripts/README.adoc
kafka-bin-scripts/quickstart.yml
kafkacat/README.adoc
kafkacat/quickstart.yml

This PR updates the _Kafka scripts_ and _Kafkacat_ quick starts. 
- Changes the titles to _Configuring and connecting..._ rather than _Using..._ 
- Replaces _bin scripts_ with _scripts_  
- Removes the download/install step, which becomes a general prereq. Other detail moved to other sections of each quick start
- Adds a line about using the Kafka scripts to check a new Kafka instance to _Getting Started_
- Removes group Id config (not currently working)
NOTE
- The PR doesn't change Kafkacat to kcat (pending a decision on that)
- The version check (`-version` and `-V`) is moved to a portal-only section
Details: [MGDSTRM-5099](https://issues.redhat.com/browse/MGDSTRM-5099)
PORTAL DOC
- [Kafkacat quick …

docs: scripts and kafkacat quickstarts updates

---

consumer-configuration/README.adoc

Fixed minor typos in `consumer-configuration/README.adoc`

docs: fix typos in consumer-config

---

.build/src/app/QuickStartContainer.tsx

In prod the fix depends on
https://github.com/RedHatInsights/insights-chrome/pull/1670
The change in this PR is to ensure that while running locally it is also fixed

fix pluralization rules when running locally

---

topic-configuration/README.adoc

**Notes for reviewers:**
- An HTML preview is available for review [here](http://file.emea.redhat.com/~jbyrne/j4974/README.html#con-using-kafka-topics-with-registry-schemas_configuring-topics).
- Although we've been calling this feature topic-to-schema _mapping_ internally, I shifted away from that term because 
there is no notion of a map (as far as I am aware) underpinning the linkages between topics and schemas. Just appropriate use of IDs (and ID strategy) in client application code. I think _association_ works well an alternative, in the couple of cases where it's needed.
- I drafted this documentation on the assumption that we will resolve the usability bug described [here](https://docs.google.com/document/d/1Dkf7LWjNCurrNcMG40sCSuYakz9hOdKkAqsuCYsM3gM/edit#heading=h.9ux0cdzfoi1h).

Docs: Create conceptual and procedural content for topic-to-schema mapping

---

rhoas-cli/README.adoc

Reverts redhat-developer/app-services-guides#373 
After checking release process today I see that release involves number of manual steps (overall 3 hours of engineering time vs 1 minute upstream) and also requires jira tickets for teams that are not accessible for holiday period.
I'm really concerned about lack of ability to release in timely fashion over holiday period. 
This PR reverts changes we have made and restores upstream releases process for the short time (+2 sprints) the issues with downstream process will be resolved

Revert "Update CLI install guide"

---

.github/workflows/modular-docs-publish.yml
CONTRIBUTING.adoc

Following number of issues related to the frequent updates of Guides and CLI we going to be moving to release on demand. 
When we want to perform release we need to create github tag as outlined in the procedure.

Upstream release process

---

docs/kafka/nodejs-kafka/README.adoc
docs/kafka/rhoas-cli-getting-started-kafka/README.adoc
docs/kafka/service-binding-kafka/README.adoc
docs/registry/getting-started-registry/README.adoc
docs/registry/quarkus-registry/README.adoc
docs/registry/rhoas-cli-getting-started-registry/README.adoc
docs/rhoas/rhoas-cli-installation/README.adoc

@smccarthy-ie Discovered in sanity checks this publish that some of the URLs that were displayed from certain cross-refs in the docs were showing the attributes. I believe this is do to the format `see link:{variable}` instead of just `see {variable}`, which this PR fixes throughout the docs project.

Clean up dirty URLs

---

docs/kafka/kafka-bin-scripts-kafka/README.adoc

Restores caption markup for some code blocks. The period preceding some of these was removed in error, causing them to be styled as plain text in the published docs.

Restore captions for some code blocks

---

docs/kafka/getting-started-kafka/README.adoc
docs/kafka/getting-started-kafka/quickstart.yml
docs/kafka/kafka-bin-scripts-kafka/README.adoc
docs/kafka/kafka-bin-scripts-kafka/quickstart.yml
docs/kafka/kcat-kafka/README.adoc
docs/kafka/kcat-kafka/quickstart.yml
docs/kafka/quarkus-kafka/README.adoc
docs/kafka/quarkus-kafka/quickstart.yml
docs/registry/quarkus-registry/README.adoc
docs/registry/quarkus-registry/quickstart.yml

Removed and amended JDK prerequisite in kafka getting started guides.

Amended prerequisite for JDK in kafka getting started guides.

---

docs/registry/access-mgmt-registry/README.adoc

**DOCUMENTATION UPDATE**
Adds a new procedure to the _Managing account access in OpenShift Service Registry_ guide.
The procedure describes how an org admin can grant access for users to view other users.
Once set, the user can view and assign other users to Service Registry instances.

docs: adds user account access to service registry access management

---

CONTRIBUTING.adoc
README.adoc

Cleans up project readme files - fixes broken links, adds missing links and attributes on:
- https://github.com/redhat-developer/app-services-guides
- https://github.com/redhat-developer/app-services-guides/blob/main/CONTRIBUTING.adoc

fix links and attributes on project readme pages

---

docs/kafka/metrics-monitoring-kafka/README.adoc

Fix step about grafana in metrics instructions.
@wtrocki can you re-review and re-approve? Here's the [doc preview](http://file.rdu.redhat.com/~sterobin/JK-7753/README.html#proc-configuring-metrics-prometheus_monitoring-metrics). I spoke with @DuncanDoyle and he pointed out that what was here before wasn't technically correct (the grafana dashboard of course isn't imported in prometheus but in grafana). Anyway, I fixed it and moved things around slightly to make more sense, and Duncan approved. If you agree, can you approve this PR so we can merge to fix it? Thanks.

Fix grafana step

---

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc
docs/registry/rhoas-cli-getting-started-registry/README.adoc

Modify CLI guides to include context commands while working with services.
To be merged after #448 .

docs(cli): update cli guides with contexts

---

docs/kafka/getting-started-kafka/README.adoc

Added an additional resource to the Kafka GS quick start to point users to the Kafka Overview page that contains the info about how to purchase a subscription. 
As an additional resource, this won't show up in the quick start itself (the additional resources are only included in the customer portal version). I don't see a great way to add the pointer to the purchasing info to the quick start itself. The conclusion would probably be the best place, but it's already got a fair amount going on.

Add purchasing additional resource to GS quick start

---

code-examples/quarkus-service-registry-quickstart/consumer/pom.xml
code-examples/quarkus-service-registry-quickstart/consumer/src/main/resources/application.properties
code-examples/quarkus-service-registry-quickstart/producer/pom.xml
code-examples/quarkus-service-registry-quickstart/producer/src/main/resources/application.properties

This PR addresses two things:
- Use token endpoint instead of auth URL + realm.
- Update Quarkus version used in example.

Use token endpoint apicurio serdes

---

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc

@jbyrne-redhat Got another really minor fix that needs to be reviewed. In this case, there's just a mis-formatted code-block title.

Fix command block title in Kafka RHOAS CLI getting started guide

---

docs/kafka/kcat-kafka/README.adoc

Reports have been made about missing binary name and also kcat not working at all (no messages produced on mac).
We need to make this guide functional for the summit. Any improvements appreciated.

fix: issues with kcat guide

---

docs/registry/getting-started-registry/quickstart.yml

Make Service Registry quick start visible again by setting draft status to false

Unhide service registry getting started quick start

---

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc
docs/registry/rhoas-cli-getting-started-registry/README.adoc

Documentation has been updated as certain context sub-commands were renamed.
`rhoas context use-kafka` => `rhoas context set-kafka`
`rhoas context use-service-registry` => `rhoas context set-service-registry`
For [app-services-cli/1542](https://github.com/redhat-developer/app-services-cli/pull/1542)

docs: change cli guides with updated command names

---

docs/kafka/rhoas-cli-getting-started-kafka/README.adoc

The existing sect ID was causing a broken link in the hand-created "TOC" at the top of the guide.

Fix sect ID causing broken link

---

docs/kafka/metrics-monitoring-kafka/README.adoc

Metrics guide should follow the same pattern to tell users to copy token url from UI and CLI. 
Alternatively we can give them curl to obtain that value (if somehow they did not copied it before)
Source: https://issues.redhat.com/browse/MGDSTRM-8460

fix: add metrics token support

---

docs/kafka/nodejs-kafka/README.adoc

Just going through some of the guides node with Kafka and there were some issues.
The example code used in the example [here](https://github.com/nodeshift-starters/reactive-example) uses different environment variables for consumer and producer backends. The specific code examples are below.
- [Consumer](https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/consumer-backend/consumer.js#L26-L32)
- [Producer](https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/producer-backend/producer.js#L17-L23)
Also in the docs it mentions creating a file called `rhoas.env` this did not set the environment variables even in root or the working directory. Changing this to `.env` worked.

Incorrect environment variables and env file name

---

docs/kafka/getting-started-kafka/README.adoc
docs/kafka/kafka-bin-scripts-kafka/README.adoc
docs/kafka/topic-configuration-kafka/README.adoc

- For HTML previews of the notes added to the _Configuring topics_ and _Getting started_ guides, see [here](http://file.emea.redhat.com/~jbyrne/JK-8497/README.html#ref-supported-topic-properties_configuring-topics) and [here](http://file.emea.redhat.com/~jbyrne/JK-8497/README1.html#proc-creating-kafka-topic_getting-started).

Add notes for topic partition error situation

---

docs/kafka/getting-started-kafka/README.adoc

Implemented latest QE feedback from https://issues.redhat.com/browse/MGDSTRM-7613:
- In section Creating a service account to connect to a Kafka instance in Streams for Apache Kafka, step 4, there is: "Enter a unique service account name, such as my-service-account, add an optional description, and click Create.".
There is not a unique service account name and an optional description anymore, there is Short description only now.
- In section Creating a service account to connect to a Kafka instance in Streams for Apache Kafka, step 5, there is: "...Client Secret...".
It is "...Client secret..." (lowercase "s" instead of uppercase).
- In section Creating a Kafka topic in Streams for Apache Kafka, step 2, item Replicas, there is sentence: "The number of partition replicas for the topic is …

Implemented latest QE feedback in Getting Started with RHOSAK guide

---

docs/kafka/metrics-monitoring-kafka/README.adoc

As per request in https://issues.redhat.com/browse/MGDSTRM-8887:
'The maximum number of topics is 1000 for all Kafka instances.
This should be either removed or kept up-to-date with increased limits per SU. Not mentioning specific limits in this doc can make maintaining it simpler, so I suggest removing this sentence.'

Removed max number of topics per KI sentence.

---

docs/rhoas/rhoas-service-contexts/README.adoc

The xref in question was pointing to the wrong section. However, the link is not actually needed, so I simply removed it.

docs: Remove broken xref

---

docs/database-access/accessing-the-database-access-menu-for-configuring-and-monitoring/quickstart.yml
docs/database-access/connecting-an-application-to-a-database-instance-using-the-topology-view/quickstart.yml

Minor edits from install party feedback.
IMPORTANT:
We have a CCS exception for not publishing the README.adoc files with these quick starts at this time.  This exception will last until the RHODA beta release, at which time we will conform to the current standard.  Please see Christy Watkins comment on 3/8/22 in Jira [RHCLOUD-17582](https://issues.redhat.com/browse/RHCLOUD-17582) for this CCS exception.

Minor edits to QSGs

---

.build/webpack.common.js

remove all eager loading as we should never eagerly load any dependency ever; when eagerly loading, the dependency gets bundled with the bundle that will be loaded through module federation, forcing users to download them all over again

chore: don't eagerly load dependencies

---

docs/kafka/message-browsing-kafka/README.adoc
docs/kafka/metrics-monitoring-kafka/README.adoc

Made the following updates in this preview of the [Messages](http://file.ams.redhat.com/aecollin/JK-9743/Messages/README.html) guide:
- Broke 2nd sentence into list for improved readability
- Amended one instance of 'console' to 'web console'
- Ensured full name of product used on first occurrence in each module
- Replaced 'drop-down menu- with 'list'
- Removed italics for guide links
- Removed references to 'offset' as default value and amended this default value to 'latest messages'
- Corrected typo
Made the following updates in this preview of the [Metrics](http://file.ams.redhat.com/aecollin/JK-9743/Metrics/README.html) guide:
- Amended 'refer to' to 'see'
- Added ^ symbol to external links
- Ensured full name of product used on first occurrence in each module
- Changed 'Kafkacat' to …

Updated Metrics and Messages guides according to agreed style guidelines

---

README.adoc
docs/kafka/getting-started-kafka/README.adoc
docs/kafka/kcat-kafka/README.adoc
docs/kafka/kcat-kafka/quickstart.yml
docs/registry/getting-started-registry/README.adoc

This PR includes the following updates:
- Updates the [Kafkacat quick start](https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/ee92cfdb-9587-42f8-80d5-54169e0e3c07) to reference Kcat (the new name). This includes all of the commands.
- Updates references to Kafkacat in other MAS guides
- Applies [MAS style updates](https://docs.google.com/document/d/1TERH4XRH6La44hUQH88LUaax-35JH3dLXmceGJoLv7I/edit#) to the quick start
An HTML preview of the updated quick start is available [here](http://file.emea.redhat.com/~jbyrne/JK-9559/README.html).

docs: update Kafkacat to Kcat

---

docs/kafka/getting-started-kafka/README.adoc
docs/kafka/nodejs-kafka/README.adoc
docs/kafka/quarkus-kafka/README.adoc
docs/rhoas/rhoas-produce-consume/README.adoc

- For the Getting Started quick start, introduced conditionlization for the console and Customer Portal versions of quick start.
- For the Quarkus and Node.js quick starts, trimmed the topic creation procedure to no longer use a figure. This made any further conditionalization unnecessary.
- Made a minor (unrelated to figures) update to docs/rhoas/rhoas-produce-consume/README.adoc to keep this in line with the Quarkus and Node.js quick starts
- Generated console versions of quick starts locally to verify that updates look as intended.
- Also verified Customer Portal versions locally.

docs: JK-10139: updates to ensure that OpenShift Streams console quick starts don't refer to figures

---

docs/kafka/access-mgmt-kafka/README.adoc
docs/kafka/getting-started-kafka/README.adoc
docs/kafka/service-binding-kafka/README.adoc
docs/registry/service-binding-registry/README.adoc
docs/rhoas/rhoas-service-contexts/README.adoc

- As discussed in https://issues.redhat.com/browse/MGDSTRM-6383, removing incorrect statement (in a few guides) that says that the example ACL permissions shown allow applications to "use any producer". This is not the case.
- Also as discussed in the JIRA, there are a couple of instances where we incorrectly state that the example ACL permissions allow applications associated with the service account to delete topics. In fact, only the "Create" operation is set.
- HTML previews for the _Getting Started_ and _Access Management_ guides are [here](http://file.emea.redhat.com/~jbyrne/JK-6383/Getting%20started%20with%20OpenShift%20Streams%20for%20Apache%20Kafka.html) and [here](http://file.emea.redhat.com/~jbyrne/JK-6383/Managing%20account%20access%20in%20OpenShift%20St …

docs: JK-6383: update guides to correctly describe configured ACL permissions

---

docs/rhoas/iac_tools_rhoas/README.adoc

- Refined guide by breaking large procedures into several smaller ones.
- Corrected a few typos.
- Replaced raw URLs with linked text to aid screenreaders
- Added a note to a step to improve readability 
- Note to reviewers: preview available [here](http://file.ams.redhat.com/aecollin/JK-10345/README.html).

docs: JK-10345: Refined IaC guide and broke procedures into smaller ones

---

docs/kafka/kafka-bin-scripts-kafka/README.adoc

When using the OAuthBearerLoginCallbackHandler (as specified as the value for `sasl.login.callback.handler.class` in this example config), and when using `sso.redhat.com` (or potentially other Keycloak and maybe some other OAuth servers), which we do, then without specifying a scope will currently lead to a response with an empty scope, which is invalid and leads to failure.
The `sso.redhat.com` folks have suggested `openid` as the scope value, and I've verified that it works.
This seems to be the only place where `org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler` is used in this repo, I'm not sure if it's used in any other docs or quickstarts?
Where `io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler` is used in some other cases here …

Add "scope" to sasl.jaas.config

---

CONTRIBUTING.adoc
docs/registry/access-mgmt-registry/README.adoc

Remove hard-coded URL for old version of Apicurio REST API. Adds no value in this context anyway.

docs: remove stale apicurio rest api url from sr access guide

---

README.adoc

Add note to clarify that these cloud services are no longer available and point at self-managed alternative products instead.

Update README.adoc with alternative products
